# Generated by Django 3.1.5 on 2021-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.SmallIntegerField(null=True)),
                ('room_number', models.CharField(blank=True, max_length=30, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
